### PR TITLE
fix missing class on the submenu tab

### PR DESCRIPTION
**Pull request by jacobherrington**

### CODE REVIEW

**Comment by jacobherrington** [comment]
Just a small bug that @k1bs noticed while we were working on a yotpo integration.

**Review by fastjames — APPROVED** [review]
:cake:

**Comment by fastjames** [comment]
One thing to note: our fork's master branch is behind upstream master, which appears to include quite a few changes. We should look into playing catchup.

**Comment by fastjames** [comment]
Also, is this suitable for a PR?

**Comment by jacobherrington** [comment]
@fastjames I didn't look too closely, but it appears that the usptream repo is no longer using defacements.

**Comment by fastjames** [comment]
You had my interest, now you have my attention.

**Comment by fastjames** [comment]
I just read over upstream, and you're right -- they have successfully removed `deface` altogether. I would prefer that we update to upstream master, and then reexamine the class to see if it's still needed.

**Comment by fastjames** [comment]
I have a PR for a fix that's a blocker on updating this gem, if you are interested: https://github.com/geminimvp/engine_storefront_backend_ui/pull/140

**Comment by fastjames** [comment]
I'm going to close this PR in favor of following the update path on `solidus_paypal_braintree`. If this bug still exists we will almost centainly have to do it differently in the absence of `deface`.

**Comment by jacobherrington** [comment]
Just a heads up, the menu editor that @k1bs built is using deface so might need to revisit that

**Comment by jacobherrington** [comment]
I believe that Theme Editor is as well.

**Comment by k1bs** [comment]
The theme editor and menu editors are both currently using Deface.

**Comment by fastjames** [comment]
Sorry, I should have been more clear -- this extension now inserts its modifications without using deface.

**Pull request closed without merging**
